# Generated by Django 4.2.5 on 2023-10-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0002_avatar_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
    ]
