# Generated by Django 4.2.5 on 2023-10-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0003_rename_user_avatar_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CremasCorporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cremasfaciales',
            name='color',
        ),
        migrations.AddField(
            model_name='accesorio',
            name='autor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cremasfaciales',
            name='autor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maquillaje',
            name='autor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(default='false', max_length=40),
        ),
    ]
