# Generated by Django 4.2.5 on 2023-10-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0004_cremascorporales_remove_cremasfaciales_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgProductos/accesorios'),
        ),
        migrations.AddField(
            model_name='cremascorporales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgProductos/cremasCorporales'),
        ),
        migrations.AddField(
            model_name='cremasfaciales',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgProductos/cremasFaciales'),
        ),
        migrations.AddField(
            model_name='maquillaje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imgProductos/maquillajes'),
        ),
    ]
