# Generated by Django 4.2.5 on 2023-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoApp', '0005_accesorio_imagen_cremascorporales_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquillaje',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
